### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by singchung** [dereklokgithub/PSM-UAT#13]
1. please remove Map on the top
2. please change address text, just put our email & tel number is enough? lets discuss
   email: helen.chan@primestylemart.com
   Tel: +852 2660 4433
   Fax: +852 2666 6503
3. this email is also for enquiry form email
   login: helen.chan@primestylemart.com
   password: kfnh1275
   Email server: exchange.hk.pico.com
   SMTP port : 587 (Non-SSL), is for external server.
4. Remove category thing under the address
   ![image](https://cloud.githubusercontent.com/assets/19768722/15850054/79417e30-2cc8-11e6-9e1d-c0422ebab3e3.png)

**Comment by shirshirmok** [comment]
Fixed #1 and #4. Awaiting for complete email list.
