### ISSUE TITLE
footer item

### ISSUE THREAD

**Issue by singchung** [dereklokgithub/PSM-UAT#19]
Column 1 - About Us
- About
- Corporate Gifts
- Branded Product
- Life Style

Column 2 - Prime Style Mart
- Terms & Conditions
- Privacy Policy
- Shipping Rate?

Column 3 - Support
- My Account
- Contact Us
- Customized Services

Column 4 - We Accept
3 payment logo is ok

**Comment by singchung** [comment]
column 2 should be Prime Style Mart instead?
![screen shot 2016-06-14 at 12 17 14 pm](https://cloud.githubusercontent.com/assets/19768722/16031091/2324edae-322a-11e6-8afa-fa4c731f1b88.png)

**Comment by shirshirmok** [comment]
Just corrected to "PRIME STYLE MART"
