### ISSUE TITLE
MAC - calculation problem

### ISSUE THREAD

**Issue by singchung** [dereklokgithub/PSM-UAT#41]
wrong total value for all products, except furnitures 
![screen shot 2016-06-10 at 12 25 18 pm](https://cloud.githubusercontent.com/assets/19768722/15954377/dda22414-2f08-11e6-973d-4b5ce4313a59.png)
![screen shot 2016-06-10 at 12 41 51 pm](https://cloud.githubusercontent.com/assets/19768722/15954376/dd38a6d8-2f08-11e6-96ee-7ce7a3dbd13c.png)
![screen shot 2016-06-10 at 12 31 21 pm](https://cloud.githubusercontent.com/assets/19768722/15954379/dda3dae8-2f08-11e6-8f2f-729a160e6661.png)
![screen shot 2016-06-10 at 12 32 11 pm](https://cloud.githubusercontent.com/assets/19768722/15954380/dda84970-2f08-11e6-8515-06f048aaaca7.png)
![screen shot 2016-06-10 at 12 33 11 pm](https://cloud.githubusercontent.com/assets/19768722/15954378/dda30c4e-2f08-11e6-96b1-31b341f3cc47.png)

**Comment by shirshirmok** [comment]
All prices will round down to 1 decimal place.

**Comment by singchung** [comment]
Please refer to issue#51
