### ISSUE TITLE
Change KV image

### ISSUE THREAD

**Issue by singchung** [dereklokgithub/PSM-UAT#8]
Desktop 1200px x 400px
Mobile 480px x 500px

will send you revised image by separate email

**Comment by singchung** [comment]
KV is still old version ,please help to check

**Comment by singchung** [comment]
one of KV is old version

**Comment by shirshirmok** [comment]
Modified, please check again. 
![2016-06-16 11 01 48](https://cloud.githubusercontent.com/assets/19773700/16104194/a8e72262-33b1-11e6-839e-a96bd0d4c3cb.png)
